### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by picnic-yu** [nodece/react-ts-starter#1]
cnpm i 
npm run dev 服务运行不起来

**Comment by nodece** [comment]
@picnic-yu 请提供错误信息，建议使用 yarn 包管理工具

**Comment by picnic-yu** [comment]
[at-loader] ./node_modules/_antd@2.13.14@antd/lib/form/Form.d.ts:107:63
    TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

**Comment by nodece** [comment]
@picnic-yu  建议降低下 typescript 版本，可以尝试下使用 2.7 版本，当时忘记配置 typescript 版本了，本项目未提供 npm 依赖版本锁定，建议使用 yarn 。

**Comment by picnic-yu** [comment]
yarn安装依赖运行环境已经跑起来了，但是npm run build 出现了错误。

ERROR in ./node_modules/antd/lib/button/style/index.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../../style/themes/default";
| @import "../../style/mixins/index";
| @import "./mixin";
 @ ./node_modules/antd/lib/button/style/index.js 5:0-23
 @ ./src/components/Main.tsx
 @ ./src/routes/index.tsx
 @ ./src/App.tsx
 @ ./src/index.tsx
 @ multi ./src/index.tsx

ERROR in ./node_modules/antd/lib/style/index.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "./themes/default";
| @import "./core/index";
|
 @ ./node_modules/antd/lib/button/style/index.js 3:0-33
 @ ./src/components/Main.tsx
 @ ./src/routes/index.tsx
 @ ./src/App.tsx
 @ ./src/index.tsx
 @ multi ./src/index.tsx

**Comment by nodece** [comment]
@picnic-yu 目前该仓库仅供学习，无法用于生产环境。
